# Lines configured by zsh-newuser-install
HISTFILE=~/.zhistfile
HISTSIZE=10000
SAVEHIST=10000
setopt appendhistory autocd beep notify
# End of lines configured by zsh-newuser-install
# The following lines were added by compinstall
zstyle :compinstall filename '/home/jack/.zshrc'

autoload -Uz compinit
compinit
# End of lines added by compinstall

# case-insensitive completion
zstyle ':completion:*' matcher-list 'm:{a-zA-Z}={A-Za-z}'

# use vi-style, but keep some useful things
bindkey -v
bindkey '^p' up-line-or-history
bindkey '^n' down-line-or-history
bindkey '^r' history-incremental-search-backward
bindkey '\e[3~' delete-char
bindkey '^_' backward-kill-word
# vi escape
KEYTIMEOUT=1

# git branch in prompt
autoload -Uz vcs_info
precmd() { vcs_info }
zstyle ':vcs_info:git:*' formats '%F{yellow}(%b) '

setopt PROMPT_SUBST
PROMPT='%~ ${vcs_info_msg_0_}%(?.%F{blue}.%F{red})%#$_NORMAL_MODE_PROMPT%f'

_NORMAL_MODE_PROMPT=" "
function zle-line-init zle-keymap-select {
    # change the prompt when changing vi modes
    _NORMAL_MODE_PROMPT=" "
    if [[ "$KEYMAP" == "vicmd" ]]; then
        _NORMAL_MODE_PROMPT="%F{yellow}*"
    fi
    zle reset-prompt
}
zle -N zle-line-init
zle -N zle-keymap-select

# set the terminal background
# ~/scripts/set-term-bg.sh

EDITOR=vim
source ~/.aliases
[ -f ~/.zshrc.local ] && source ~/.zshrc.local

export PATH=~/bin:$PATH
export JAVA_HOME=$(/usr/libexec/java_home -v 1.8)
export PATH=$JAVA_HOME/bin:$PATH

[ -f ~/.fzf.zsh ] && source ~/.fzf.zsh
