# Lines configured by zsh-newuser-install
HISTFILE=~/.zhistfile
HISTSIZE=1000
SAVEHIST=1000
setopt appendhistory autocd beep notify
# End of lines configured by zsh-newuser-install
# The following lines were added by compinstall
zstyle :compinstall filename '/home/jack/.zshrc'

autoload -Uz compinit
compinit
# End of lines added by compinstall

source ~/.aliases

# case-insensitive completion
zstyle ':completion:*' matcher-list 'm:{a-zA-Z}={A-Za-z}'

# use vi-style, but keep some useful things
bindkey -v
bindkey '^p' up-line-or-history
bindkey '^n' down-line-or-history
bindkey '\e[3~' delete-char
# vi escape
KEYTIMEOUT=1

# change the prompt when changing vi modes
function zle-line-init zle-keymap-select {
    NORMAL_MODE_PROMPT=" "
    if [[ "$KEYMAP" == "vicmd" ]]; then
        NORMAL_MODE_PROMPT="%F{yellow}_%f"
    fi
    PROMPT="%~ %(?.%F{blue}.%F{red})%#%f$NORMAL_MODE_PROMPT"
    zle reset-prompt
}
zle -N zle-line-init
zle -N zle-keymap-select

# set the terminal background
~/scripts/set-term-bg.sh

EDITOR=vim

[[ -n "$MYENV" ]] && source activate.sh $MYENV
# the above is sometimes false, so let's override it
true
