# Lines configured by zsh-newuser-install
HISTFILE=~/.zhistfile
HISTSIZE=1000
SAVEHIST=1000
setopt appendhistory autocd beep notify
bindkey -v
# End of lines configured by zsh-newuser-install
# The following lines were added by compinstall
zstyle :compinstall filename '/home/jack/.zshrc'

autoload -Uz compinit
compinit
# End of lines added by compinstall

source ~/.aliases

# case-insensitive completion
zstyle ':completion:*' matcher-list 'm:{a-zA-Z}={A-Za-z}'

# set the terminal background
~/scripts/set-term-bg.sh

EDITOR=vim
PROMPT='%~ %(?.%F{blue}.%F{red})%#%f '

[[ -n "$MYENV" ]] && source activate.sh $MYENV
# the above is sometimes false, so let's override it
true
